name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy over SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd ${{ secrets.SERVER_PATH }}
          PREV_COMMIT=$(git rev-parse HEAD)
          git pull origin main || exit 1
          docker compose build || {
            git reset --hard "$PREV_COMMIT"
            exit 1
          }
          docker compose up -d || {
            git reset --hard "$PREV_COMMIT"
            docker compose build && docker compose up -d
            exit 1
          }

